# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/zhangyang/Documents/Assignments/CG/HW2/src/CMakeLists.txt))

/Users/zhangyang/Documents/Assignments/CG/HW2/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.21.3_1/bin/cmake -H/Users/zhangyang/Documents/Assignments/CG/HW2 -B/Users/zhangyang/Documents/Assignments/CG/HW2
